[2019-01-27 11:55:51,828] {logging_mixin.py:95} INFO - Sending to executor.
[2019-01-27 11:55:51,829] {logging_mixin.py:95} INFO - [2019-01-27 11:55:51,829] {base_executor.py:56} INFO - Adding to queue: airflow run first_test print_results 2019-01-29T00:00:00+00:00 --local -sd DAGS_FOLDER/.ipynb_checkpoints/DAG-checkpoint.py
[2019-01-27 11:55:51,831] {logging_mixin.py:95} INFO - [2019-01-27 11:55:51,831] {sequential_executor.py:45} INFO - Executing command: airflow run first_test print_results 2019-01-29T00:00:00+00:00 --local -sd DAGS_FOLDER/.ipynb_checkpoints/DAG-checkpoint.py
[2019-01-27 11:55:52,856] {models.py:1355} INFO - Dependencies not met for <TaskInstance: first_test.print_results 2019-01-29T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'run_regression'}
[2019-01-27 11:55:52,857] {models.py:1355} INFO - Dependencies not met for <TaskInstance: first_test.print_results 2019-01-29T00:00:00+00:00 [None]>, dependency 'Execution Date' FAILED: Execution date 2019-01-29T00:00:00+00:00 is in the future (the current date is 2019-01-27T17:55:52.857065+00:00).
[2019-01-27 11:55:52,858] {logging_mixin.py:95} INFO - [2019-01-27 11:55:52,858] {jobs.py:2614} INFO - Task is not able to be run
